In [11]:
import numpy as np
import csv as csv

number_of_states = 2
number_of_actions = 2

Q = np.zeros((number_of_states, number_of_actions),dtype=np.float16)
counts = np.zeros((number_of_states, number_of_actions),dtype=np.int16)
gamma = 0.9

In [12]:
def get_alpha(state,action):
    w= counts[state][action]
    return 1/(float(w+1))

def get_values_from_sample(s):
    return int(s[0]) - 1, int(s[1]) - 1,int(s[2]) - 1,int(s[3])

def getMaxForState(new_state):
    return np.max(Q[new_state])

In [13]:
def run_Q_Learning(samples):
    for h in range(1,horizons):
        total_change = 0.0
        for s in samples:
            initial_state,action,new_state,reward = get_values_from_sample(s)
            alpha = get_alpha(initial_state,action)
            old_Q_s_a = Q[initial_state][action]
            maxForNewState = getMaxForState(new_state)
            sample = reward + gamma * maxForNewState
            Q[initial_state][action] = (1 - alpha) * old_Q_s_a + alpha * sample
            counts[initial_state][action] += 1
            change = Q[initial_state][action] - old_Q_s_a
            total_change += change
            print("State:",new_state,"Max Value:",maxForNewState)
            print Q
            print counts
        print total_change
        if(total_change < 0.01):
            print "Converged at horizon:", h
            print Q
            return
    print Q

In [14]:
def load_data():
    samples = []
    inputFilenameWithPath = 'q-learning.dat'
    with open(inputFilenameWithPath, 'rb') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        for row in reader:
            samples.append(row)
    return samples

In [15]:
horizons = 200
samples = load_data()
run_Q_Learning(samples)

('State:', 1, 'Max Value:', 0.0)
[[ 0.  0.]
 [ 0.  0.]]
[[0 1]
 [0 0]]
('State:', 0, 'Max Value:', 0.0)
[[ 0.  0.]
 [ 2.  0.]]
[[0 1]
 [1 0]]
('State:', 0, 'Max Value:', 0.0)
[[ 0.   1.5]
 [ 2.   0. ]]
[[0 2]
 [1 0]]
('State:', 0, 'Max Value:', 1.5)
[[ 0.          2.44921875]
 [ 2.          0.        ]]
[[0 3]
 [1 0]]
('State:', 0, 'Max Value:', 2.4492)
[[ 3.20507812  2.44921875]
 [ 2.          0.        ]]
[[1 3]
 [1 0]]
('State:', 1, 'Max Value:', 2.0)
[[ 3.00195312  2.44921875]
 [ 2.          0.        ]]
[[2 3]
 [1 0]]
('State:', 0, 'Max Value:', 3.002)
[[ 3.00195312  2.44921875]
 [ 3.3515625   0.        ]]
[[2 3]
 [2 0]]
('State:', 0, 'Max Value:', 3.002)
[[ 3.234375    2.44921875]
 [ 3.3515625   0.        ]]
[[3 3]
 [2 0]]
('State:', 0, 'Max Value:', 3.2344)
[[ 3.40429688  2.44921875]
 [ 3.3515625   0.        ]]
[[4 3]
 [2 0]]
('State:', 0, 'Max Value:', 3.4043)
[[ 3.40429688  3.35351562]
 [ 3.3515625   0.        ]]
[[4 4]
 [2 0]]
('State:', 0, 'Max Value:', 3.4043)
[[ 3.53710938

('State:', 0, 'Max Value:', 7.1172)
[[ 6.1015625   7.1171875 ]
 [ 6.9296875   5.06640625]]
[[68 34]
 [21 13]]
('State:', 0, 'Max Value:', 7.1172)
[[ 6.1015625   7.18359375]
 [ 6.9296875   5.06640625]]
[[68 35]
 [21 13]]
('State:', 0, 'Max Value:', 7.1836)
[[ 6.12109375  7.18359375]
 [ 6.9296875   5.06640625]]
[[69 35]
 [21 13]]
('State:', 1, 'Max Value:', 6.9297)
[[ 6.13671875  7.18359375]
 [ 6.9296875   5.06640625]]
[[70 35]
 [21 13]]
('State:', 1, 'Max Value:', 6.9297)
[[ 6.13671875  7.18359375]
 [ 6.9296875   5.1484375 ]]
[[70 35]
 [21 14]]
0.84765625
('State:', 1, 'Max Value:', 6.9297)
[[ 6.13671875  7.15625   ]
 [ 6.9296875   5.1484375 ]]
[[70 36]
 [21 14]]
('State:', 0, 'Max Value:', 7.1562)
[[ 6.13671875  7.15625   ]
 [ 7.          5.1484375 ]]
[[70 36]
 [22 14]]
('State:', 0, 'Max Value:', 7.1562)
[[ 6.13671875  7.21875   ]
 [ 7.          5.1484375 ]]
[[70 37]
 [22 14]]
('State:', 0, 'Max Value:', 7.2188)
[[ 6.13671875  7.27734375]
 [ 7.          5.1484375 ]]
[[70 38]
 [22 14]]

 [ 48  32]]
('State:', 0, 'Max Value:', 8.4375)
[[ 7.2109375  8.4375   ]
 [ 8.171875   6.1328125]]
[[160  81]
 [ 49  32]]
('State:', 0, 'Max Value:', 8.4375)
[[ 7.2109375  8.4609375]
 [ 8.171875   6.1328125]]
[[160  82]
 [ 49  32]]
('State:', 0, 'Max Value:', 8.4609)
[[ 7.2109375  8.484375 ]
 [ 8.171875   6.1328125]]
[[160  83]
 [ 49  32]]
('State:', 0, 'Max Value:', 8.4844)
[[ 7.21875    8.484375 ]
 [ 8.171875   6.1328125]]
[[161  83]
 [ 49  32]]
('State:', 1, 'Max Value:', 8.1719)
[[ 7.2265625  8.484375 ]
 [ 8.171875   6.1328125]]
[[162  83]
 [ 49  32]]
('State:', 0, 'Max Value:', 8.4844)
[[ 7.2265625  8.484375 ]
 [ 8.203125   6.1328125]]
[[162  83]
 [ 50  32]]
('State:', 0, 'Max Value:', 8.4844)
[[ 7.234375   8.484375 ]
 [ 8.203125   6.1328125]]
[[163  83]
 [ 50  32]]
('State:', 0, 'Max Value:', 8.4844)
[[ 7.2421875  8.484375 ]
 [ 8.203125   6.1328125]]
[[164  83]
 [ 50  32]]
('State:', 0, 'Max Value:', 8.4844)
[[ 7.2421875  8.5078125]
 [ 8.203125   6.1328125]]
[[164  84]
 [ 50  32]

 [ 98  64]]
('State:', 0, 'Max Value:', 9.5078)
[[ 8.1328125  9.5078125]
 [ 9.1328125  6.984375 ]]
[[325 164]
 [ 98  64]]
('State:', 0, 'Max Value:', 9.5078)
[[ 8.140625   9.5078125]
 [ 9.1328125  6.984375 ]]
[[326 164]
 [ 98  64]]
('State:', 0, 'Max Value:', 9.5078)
[[ 8.1484375  9.5078125]
 [ 9.1328125  6.984375 ]]
[[327 164]
 [ 98  64]]
('State:', 1, 'Max Value:', 9.1328)
[[ 8.1484375  9.5078125]
 [ 9.1328125  6.984375 ]]
[[328 164]
 [ 98  64]]
('State:', 1, 'Max Value:', 9.1328)
[[ 8.1484375   9.5078125 ]
 [ 9.1328125   7.00390625]]
[[328 164]
 [ 98  65]]
('State:', 0, 'Max Value:', 9.5078)
[[ 8.1484375   9.5078125 ]
 [ 9.1484375   7.00390625]]
[[328 164]
 [ 99  65]]
('State:', 0, 'Max Value:', 9.5078)
[[ 8.1484375   9.5234375 ]
 [ 9.1484375   7.00390625]]
[[328 165]
 [ 99  65]]
('State:', 0, 'Max Value:', 9.5234)
[[ 8.15625     9.5234375 ]
 [ 9.1484375   7.00390625]]
[[329 165]
 [ 99  65]]
('State:', 1, 'Max Value:', 9.1484)
[[ 8.15625     9.5234375 ]
 [ 9.1484375   7.00390625]]
[

('State:', 0, 'Max Value:', 9.9453)
[[ 8.296875   9.953125 ]
 [ 9.6484375  7.5      ]]
[[490 247]
 [148  98]]
('State:', 0, 'Max Value:', 9.9531)
[[ 8.296875   9.9609375]
 [ 9.6484375  7.5      ]]
[[490 248]
 [148  98]]
('State:', 0, 'Max Value:', 9.9609)
[[ 8.296875   9.9609375]
 [ 9.6484375  7.5      ]]
[[491 248]
 [148  98]]
('State:', 1, 'Max Value:', 9.6484)
[[ 8.296875   9.9609375]
 [ 9.6484375  7.5      ]]
[[492 248]
 [148  98]]
('State:', 0, 'Max Value:', 9.9609)
[[ 8.296875   9.9609375]
 [ 9.65625    7.5      ]]
[[492 248]
 [149  98]]
('State:', 0, 'Max Value:', 9.9609)
[[ 8.296875   9.9609375]
 [ 9.65625    7.5      ]]
[[493 248]
 [149  98]]
('State:', 0, 'Max Value:', 9.9609)
[[ 8.296875   9.9609375]
 [ 9.65625    7.5      ]]
[[494 248]
 [149  98]]
('State:', 0, 'Max Value:', 9.9609)
[[ 8.296875  9.96875 ]
 [ 9.65625   7.5     ]]
[[494 249]
 [149  98]]
('State:', 0, 'Max Value:', 9.9688)
[[ 8.296875  9.96875 ]
 [ 9.65625   7.5     ]]
[[495 249]
 [149  98]]
('State:', 0, 'Max

[[658 330]
 [198 131]]
('State:', 0, 'Max Value:', 10.352)
[[  8.296875    10.3515625 ]
 [ 10.0390625    7.83984375]]
[[659 330]
 [198 131]]
('State:', 1, 'Max Value:', 10.039)
[[  8.296875    10.3515625 ]
 [ 10.0390625    7.83984375]]
[[660 330]
 [198 131]]
('State:', 1, 'Max Value:', 10.039)
[[  8.296875    10.3515625 ]
 [ 10.0390625    7.84765625]]
[[660 330]
 [198 132]]
0.0625
('State:', 1, 'Max Value:', 10.039)
[[  8.296875    10.34375   ]
 [ 10.0390625    7.84765625]]
[[660 331]
 [198 132]]
('State:', 0, 'Max Value:', 10.344)
[[  8.296875    10.34375   ]
 [ 10.046875     7.84765625]]
[[660 331]
 [199 132]]
('State:', 0, 'Max Value:', 10.344)
[[  8.296875    10.3515625 ]
 [ 10.046875     7.84765625]]
[[660 332]
 [199 132]]
('State:', 0, 'Max Value:', 10.352)
[[  8.296875    10.359375  ]
 [ 10.046875     7.84765625]]
[[660 333]
 [199 132]]
('State:', 0, 'Max Value:', 10.359)
[[  8.296875    10.359375  ]
 [ 10.046875     7.84765625]]
[[661 333]
 [199 132]]
('State:', 1, 'Max Value:'

 [ 10.421875    8.1015625]]
[[820 412]
 [247 164]]
('State:', 0, 'Max Value:', 10.844)
[[  8.296875   10.8515625]
 [ 10.421875    8.1015625]]
[[820 413]
 [247 164]]
('State:', 0, 'Max Value:', 10.852)
[[  8.296875   10.8515625]
 [ 10.421875    8.1015625]]
[[821 413]
 [247 164]]
('State:', 1, 'Max Value:', 10.422)
[[  8.296875   10.8515625]
 [ 10.421875    8.1015625]]
[[822 413]
 [247 164]]
('State:', 0, 'Max Value:', 10.852)
[[  8.296875   10.8515625]
 [ 10.4296875   8.1015625]]
[[822 413]
 [248 164]]
('State:', 0, 'Max Value:', 10.852)
[[  8.296875   10.8515625]
 [ 10.4296875   8.1015625]]
[[823 413]
 [248 164]]
('State:', 0, 'Max Value:', 10.852)
[[  8.296875   10.8515625]
 [ 10.4296875   8.1015625]]
[[824 413]
 [248 164]]
('State:', 0, 'Max Value:', 10.852)
[[  8.296875   10.859375 ]
 [ 10.4296875   8.1015625]]
[[824 414]
 [248 164]]
('State:', 0, 'Max Value:', 10.859)
[[  8.296875   10.859375 ]
 [ 10.4296875   8.1015625]]
[[825 414]
 [248 164]]
('State:', 0, 'Max Value:', 10.859)
[

 [296 196]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[983 493]
 [296 196]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[984 493]
 [296 196]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[984 494]
 [296 196]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[985 494]
 [296 196]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[986 494]
 [296 196]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[987 494]
 [296 196]]
('State:', 1, 'Max Value:', 10.805)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.3515625]]
[[988 494]
 [296 196]]
('State:', 1, 'Max Value:', 10.805)
[[  8.296875   11.265625 ]
 [ 10.8046875   8.359375 ]]
[[988 494]
 [296 197]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875  11.265625]
 [ 10.8125     

[[1146  574]
 [ 344  228]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875   11.265625 ]
 [ 10.921875    8.6015625]]
[[1147  574]
 [ 344  228]]
('State:', 1, 'Max Value:', 10.922)
[[  8.296875   11.265625 ]
 [ 10.921875    8.6015625]]
[[1148  574]
 [ 344  228]]
('State:', 1, 'Max Value:', 10.922)
[[  8.296875  11.265625]
 [ 10.921875   8.609375]]
[[1148  574]
 [ 344  229]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875  11.265625]
 [ 10.921875   8.609375]]
[[1148  574]
 [ 345  229]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875  11.265625]
 [ 10.921875   8.609375]]
[[1148  575]
 [ 345  229]]
('State:', 0, 'Max Value:', 11.266)
[[  8.296875  11.265625]
 [ 10.921875   8.609375]]
[[1149  575]
 [ 345  229]]
('State:', 1, 'Max Value:', 10.922)
[[  8.296875  11.265625]
 [ 10.921875   8.609375]]
[[1150  575]
 [ 345  229]]
('State:', 1, 'Max Value:', 10.922)
[[  8.296875   11.265625 ]
 [ 10.921875    8.6171875]]
[[1150  575]
 [ 345  230]]
0.015625
('State:', 1, 'Max Value:', 10.922)
[[  