In [6]:
import numpy as np
import csv as csv

number_of_states = 2
number_of_actions = 2

Q = np.zeros((number_of_states, number_of_actions),dtype=np.float16)
counts = np.zeros((number_of_states, number_of_actions),dtype=np.int16)
gamma = 0.9

In [7]:
def get_alpha(state,action):
    w= counts[state][action]
    return 1/(w+1)

def get_values_from_sample(s):
    return int(s[0]) - 1, int(s[1]) - 1,int(s[2]) - 1,int(s[3])

def getMaxForState(new_state):
    return np.max(Q[new_state])

In [8]:
def run_Q_Learning(samples):
    for h in range(1,horizons):
        total_change = 0.0
        for s in samples:
            initial_state,action,new_state,reward = get_values_from_sample(s)
            alpha = get_alpha(initial_state,action)
            old_Q_s_a = Q[initial_state][action]
            maxForNewState = getMaxForState(new_state)
            sample = reward + gamma * maxForNewState
            Q[initial_state][action] = (1 - alpha) * old_Q_s_a + alpha * sample
            counts[initial_state][action] += 1
            change = Q[initial_state][action] - old_Q_s_a
            total_change += change
            print("State:",new_state,"Max Value:",maxForNewState)
            print Q
            print counts
        print total_change
        if(total_change < 0.01):
            print "Converged at horizon:", h
            print Q
            return
    print Q

In [9]:
def load_data():
    samples = []
    inputFilenameWithPath = 'q-learning.dat'
    with open(inputFilenameWithPath, 'rb') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        for row in reader:
            samples.append(row)
    return samples

In [10]:
horizons = 200
samples = load_data()
run_Q_Learning(samples)

('State:', 1, 'Max Value:', 0.0)
[[ 0.  0.]
 [ 0.  0.]]
[[0 1]
 [0 0]]
('State:', 0, 'Max Value:', 0.0)
[[ 0.  0.]
 [ 2.  0.]]
[[0 1]
 [1 0]]
('State:', 0, 'Max Value:', 0.0)
[[ 0.  0.]
 [ 2.  0.]]
[[0 2]
 [1 0]]
('State:', 0, 'Max Value:', 0.0)
[[ 0.  0.]
 [ 2.  0.]]
[[0 3]
 [1 0]]
('State:', 0, 'Max Value:', 0.0)
[[ 1.  0.]
 [ 2.  0.]]
[[1 3]
 [1 0]]
('State:', 1, 'Max Value:', 2.0)
[[ 1.  0.]
 [ 2.  0.]]
[[2 3]
 [1 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[2 3]
 [2 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[3 3]
 [2 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[4 3]
 [2 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[4 4]
 [2 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[5 4]
 [2 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[6 4]
 [2 0]]
('State:', 0, 'Max Value:', 1.0)
[[ 1.  0.]
 [ 2.  0.]]
[[7 4]
 [2 0]]
('State:', 1, 'Max Value:', 2.0)
[[ 1.  0.]
 [ 2.  0.]]
[[8 4]
 [2 0]]
('Stat